apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimentclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviereview
  template:
    metadata:
      labels:
        app: moviereview
    spec:
      containers:
      - name: cv-app
        image: gcr.io/movie-sentiment-classifier/imgwebapp:v1
        ports:
        - containerPort: 8501
